import argparse
import sys
import time
from pathlib import Path
from typing import Dict, Any
from dotenv import load_dotenv

# Ensure project root is in sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from backend.common.pipeline import CommonIngestionPipeline
from backend.vector_pipeline.pipeline import VectorStoragePipeline
from backend.graph_pipeline.pipeline import GraphStoragePipeline

load_dotenv(PROJECT_ROOT / ".env")


def main():
    parser = argparse.ArgumentParser(
        description="Hybrid RAG Master Ingestion: Common Preprocessing -> Vector & Graph Storage"
    )
    parser.add_argument(
        "--input",
        "-i",
        default="docs/spotify_web_app_architecture.pdf",
        help="Path to source document or directory (default: docs/spotify_web_app_architecture.pdf)",
    )
    parser.add_argument(
        "--target",
        "-t",
        choices=["both", "vector", "graph"],
        default="both",
        help="Target storage pipeline: 'both' (Hybrid), 'vector' (FAISS), or 'graph' (Neo4j)",
    )
    parser.add_argument(
        "--chunk-size",
        type=int,
        default=600,
        help="Chunk size for common text splitter (default: 600)",
    )
    parser.add_argument(
        "--chunk-overlap",
        type=int,
        default=100,
        help="Chunk overlap for common text splitter (default: 100)",
    )
    parser.add_argument(
        "--mode",
        choices=["auto", "section", "page"],
        default="auto",
        help="Document parsing mode (default: auto)",
    )
    parser.add_argument(
        "--output-dir",
        "-o",
        default="faiss_index",
        help="Directory to save the FAISS vector index (default: faiss_index)",
    )
    parser.add_argument(
        "--provider",
        choices=["openai", "huggingface"],
        default="openai",
        help="Embedding provider for vector pipeline (default: openai)",
    )
    parser.add_argument(
        "--model",
        default=None,
        help="OpenAI model for knowledge graph extraction (default: gpt-4o-mini)",
    )
    parser.add_argument(
        "--concurrency",
        type=int,
        default=5,
        help="Concurrency limit for graph extraction (default: 5)",
    )
    parser.add_argument(
        "--append",
        action="store_true",
        help="Append to existing FAISS index instead of overwriting",
    )

    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.is_absolute() and not input_path.exists():
        input_path = PROJECT_ROOT / args.input
    input_path = input_path.resolve()

    if not input_path.exists():
        print(f"❌ Error: Input path does not exist: {input_path}")
        sys.exit(1)

    output_dir = Path(args.output_dir)
    if not output_dir.is_absolute():
        output_dir = (PROJECT_ROOT / args.output_dir).resolve()

    print("\n" + "█" * 80)
    print("  🚀 HYBRID RAG MASTER INGESTION PIPELINE")
    print("█" * 80)
    print(f"  Source Document     : {input_path}")
    print(f"  Pipeline Target     : {args.target.upper()} (Common -> {args.target})")
    print(f"  Chunking Strategy   : chunk_size={args.chunk_size}, overlap={args.chunk_overlap}")
    print(f"  Parsing Mode        : {args.mode}")
    print("█" * 80 + "\n")

    overall_start = time.time()

    # =========================================================================
    # STAGE 1: COMMON PIPELINE (Document Loader & Text Splitter)
    # =========================================================================
    common_pipeline = CommonIngestionPipeline(
        chunk_size=args.chunk_size,
        chunk_overlap=args.chunk_overlap,
        mode=args.mode,
        verbose=True,
    )
    documents, chunks = common_pipeline.run(input_path)

    if not chunks:
        print("❌ No chunks generated by common pipeline. Exiting.")
        sys.exit(1)

    vector_result: Dict[str, Any] = {}
    graph_result: Dict[str, Any] = {}

    # =========================================================================
    # STAGE 2A: VECTOR PIPELINE (Dense Embeddings + FAISS)
    # =========================================================================
    if args.target in ["vector", "both"]:
        print("\n" + "═" * 80)
        print("  🔹 DISPATCHING CHUNKS TO: VECTOR PIPELINE (FAISS)")
        print("═" * 80)
        vector_pipeline = VectorStoragePipeline(
            embedding_provider=args.provider,
            save_directory=output_dir,
            verbose=True,
        )
        vector_result = vector_pipeline.run_on_chunks(
            chunks=chunks,
            append_if_exists=args.append,
        )

    # =========================================================================
    # STAGE 2B: GRAPH PIPELINE (LLMGraphTransformer + Neo4j)
    # =========================================================================
    if args.target in ["graph", "both"]:
        print("\n" + "═" * 80)
        print("  🔹 DISPATCHING CHUNKS TO: GRAPH PIPELINE (NEO4J)")
        print("═" * 80)
        graph_pipeline = GraphStoragePipeline(
            model_name=args.model,
            max_concurrency=args.concurrency,
            verbose=True,
        )
        graph_result = graph_pipeline.run_on_chunks(
            chunks=chunks,
            show_progress=True,
        )

    # =========================================================================
    # MASTER SUMMARY BANNER
    # =========================================================================
    total_time = time.time() - overall_start

    print("\n" + "█" * 80)
    print("  🏆 HYBRID RAG MASTER INGESTION COMPLETED")
    print("█" * 80)
    print(f"  Target File                 : {input_path.name}")
    print(f"  Common Documents Loaded     : {len(documents)}")
    print(f"  Common Semantic Chunks      : {len(chunks)}")
    if vector_result:
        print(f"  Vector Store Index          : {vector_result.get('vector_store_directory')}")
        print(f"  Total Vectors Indexed       : {vector_result.get('total_vectors_in_store')}")
    if graph_result:
        print(f"  Neo4j Total Nodes           : {graph_result.get('neo4j_total_nodes')}")
        print(f"  Neo4j Total Relationships   : {graph_result.get('neo4j_total_relationships')}")
    print(f"  Total Execution Time        : {total_time:.2f} seconds")
    print("█" * 80 + "\n")


if __name__ == "__main__":
    main()
